### ISSUE TITLE
R packages not persistent across restarts

### ISSUE THREAD

**Issue by minorsecond** [dm3ll3n/ShinyStudio#1]
Packages installed in R via `install.packages` are not persistent across restarts. Additionally, programs installed via `apt` to support R packages (ie libgdal-dev) suffer the same fate.

Is there a way to persist installed packages & applications?

**Comment by fresh2dev** [comment]
R packages *should* persist across restarts, but that is failing due to a permissions issue. I implemented the fix and will push soon.

Installed applications/libraries/drivers will *not* persist across restarts; the RStudio/Shiny Docker image needs to be built with the necessary drivers and libraries. To do this, modify the file "rshiny_rstudio/Dockerfile". Add a `RUN` command anywhere between the first and last line to `apt-get` any apps/drivers/libs you want built into the image. After you edit the Dockerfile, rebuild the site with `setup.sh`.

**Comment by fresh2dev** [comment]
This is fixed (for me) after the latest commits. Please clone a fresh copy, setup again, and let me know if the issue persists. Note that a few other changes were included. Namely, to setup the site, use `control.sh setup` instead of `setup.sh`.
